#!/bin/bash
#SBATCH -J prec
#SBATCH -D /projects/dveiga/analysis/git/BRCA_isoforms/transdecoder_precision
#SBATCH -N 1
#SBATCH -n 32
#SBATCH --mem 200G
#SBATCH -t 0-24:00:00
#SBATCH -p compute
#SBATCH -q batch
#SBATCH -o %x.out
#SBATCH -e %x.out
set -u
dir_r=/projects/banchereau-lab/tools/3_4_4/bin
$dir_r/R CMD BATCH /projects/dveiga/analysis/git/BRCA_isoforms/transdecoder_precision/2.5-BRCA_isoforms.R

